### ISSUE TITLE
Issue with reference id 

### ISSUE THREAD

**Issue by foreigntalent** [CKOTech/checkout-opencart-plugin#18]
Hey guys, 

Trying to resolve an issue with reference id inside the checkout within opencart hoping someone is experience to provide a working solution.

Thanks.

Bob

**Comment by nicolas-maalouf-cko** [comment]
Hey @foreigntalent 

Can you please provide more details about the issue you're facing?

Thanks

**Comment by foreigntalent** [comment]
Hey Nick,

Thanks for assisting, the issue we are encountering right lies with calling the reference id inside the php file:

session_unset();
session_start();

include "api_lib.php";
include "configuration.php";
include "connection.php"; 
  
  //Ensure this is the first invokation of this page
	if($_SERVER['REQUEST_METHOD'] == "POST") 
	{
		
		if (array_key_exists("submit", $_POST))
	  unset($_POST["submit"]);
		
    $order_amount = $_POST["order_amount"];   
    $order_currency = $_POST["order_currency"];
    $customer_receipt_email = "'" . $_POST["customer_receipt_email"] . "'";
    
    
    //Creates the Merchant Object from config. If you are using multiple merchant ID's, 
		// you can pass in another configArray each time, instead of using the one from configuration.php
    $merchantObj = new Merchant($configArray);

	  // The Parser object is used to process the response from the gateway and handle the connections
	  // and uses connection.php
	  $parserObj = new Parser($merchantObj);

    //The Gateway URL can be set by using the following function, or the 
    //value can be set in configuration.php
    //$merchantObj->SetGatewayUrl("https://xxx.xxx.xx.com/api/nvp");	
	  $requestUrl = $parserObj->FormRequestUrl($merchantObj);
	
	  //This is a library if useful functions
	  $new_api_lib = new api_lib;

		//Use a method to create a unique Order ID. Store this for later use in the receipt page or receipt function.
    $order_id = $new_api_lib->getRandomString(10);  
	**$order_reference = $new_api_lib->getRandomString(10)**;  
   			
   	//Form the array to obtain the checkout session ID.									 
		$request_assoc_array = array("apiOperation"=>"CREATE_CHECKOUT_SESSION",
														 	   "order.id"=>$order_id,
														 	   "order.amount"=>$order_amount,
														     "order.currency"=>$order_currency,
															 "order.reference"=>$order_reference
														 		);
														 		
		//This builds the request adding in the merchant name, api user and password.											 		
		$request = $parserObj->ParseRequest($merchantObj, $request_assoc_array);
									
		//Submit the transaction request to the payment server
		$response = $parserObj->SendTransaction($merchantObj,$request);
		
		//Parse the response
		$parsed_array = $new_api_lib->parse_from_nvp($response);								 

		//Store the successIndicator for later use in the receipt page or receipt function.
		$successIndicator = $parsed_array['successIndicator'];
 
    //The session ID is passed to the Checkout.configure() function below.
 		$session_id = $parsed_array['session.id'];
 
    //Store the variables in the session, or a database could be used for example
    $_SESSION['successIndicator']= $successIndicator;
    $_SESSION['orderID']= $order_id;
	$_SESSION['orderReference']= $order_reference;
	 
	  $merchantID = "'" . $merchantObj->GetMerchantId() . "'";
  };
  
  ?>
  
<html>
	
    <head> 
    
	   <script src="https://xxxxxx.gateway.xxxx.com/checkout/version/40/checkout.js"
	   
               	 data-error="errorCallback"
               	 data-cancel="cancelCallback"
                 data-complete="http://xxx.com/HOSTEDCheckout_Coding/Receipt_NVP.php"
                >
       </script>

       <script type="text/javascript">
            function errorCallback(error) {
                  alert(JSON.stringify(error));
            }
            
            function completeCallback(resultIndicator, sessionVersion) {
                  alert("Result Indicator");
				  				alert(JSON.stringify(resultIndicator));
                  alert("Session Version:");
				  				alert(JSON.stringify(sessionVersion));
				  				alert("Successful Payment");
            }
           
            function cancelCallback() {
                  alert('Payment cancelled');
            
            }
       
       
						Checkout.configure({
    					merchant   : <?php echo $merchantID; ?>,
    					order      : {
        				amount     : <?php echo json_encode($order_amount); ?>,
        				currency   : <?php echo json_encode($order_currency); ?>,
        				description: 'Happy Store Online',
        				id				 : <?php echo json_encode($order_id); ?>,
						reference				 : <?php echo json_encode($order_reference); ?>,
        				item			 : {
        					brand: 'xxx',
        					description: 'Happy Store Online',
        					name: 'HostedCheckoutItem',
        					quantity: '1',
        					unitPrice: '1.00',
        					unitTaxAmount: '1.00'
        				}
            	},
    					billing    : {
    						address  : {
    							street: '300 Adelaide Street',
    							stateProvince: 'QLD',
    							city: 'Brisbane',
    							company: 'Mastercard Pty Ltd',		
    							postcodeZip: '4000',
    							country: 'AUS'
    						}
    					},
    					customer :{
    						email: <?php echo $customer_receipt_email; ?>
    				  },
    					interaction: {
        				merchant: {
            		name: 'Happy Store Online',
            			address: {
            				line1: '300 Adelaide Street',
            				line2: 'Brisbane Queensland 4000'
        					},
        					  //logo:  'https://www.albemarle-london.com/OnlineBooking/Albemarle/ShowPics/ALBAniv.png'
        				}
    					},
    					session: { 
            			id: <?php echo json_encode($session_id); ?>
       						}
						});
						
        </script>
    
    </head>
    
    <body>

What happened is during sandbox, the source code worked with trial test credentials and we we naturally swapped it with production credentials and the whole checkout stopped at one time password (OTP). When we inserted the OTP into the checkout page, we expected the transaction to be successful but it wasnt.

Ended up we went back to the page filling in card details.

We checked with the bank and found out that the reference id didnt appear in the merchant administration. Hence the failure to conclude the transaction successfully.

Thanks for your help.

Bob

**Comment by avish-bisbeehurry-cko** [comment]
Hi Bob,

Can you confirm if the code you sent above is related to [checkout.com](https://www.checkout.com/) payment gateway?

Thanks

**Comment by foreigntalent** [comment]
Hi Avish,

 

The code is related to Mastercard Payment Gateway Service (MPGS).

 

Thanks.

 

Bob

 

发件人: noreply@github.com <noreply@github.com> 代表 avish-bisbeehurry-cko
发送时间: 2018年8月13日 19:59
收件人: checkout/checkout-opencart-plugin <checkout-opencart-plugin@noreply.github.com>
抄送: foreigntalent ; Mention <mention@noreply.github.com>
主题: Re: [checkout/checkout-opencart-plugin] Issue with reference id (#18)

 

Hi Bob,

Can you confirm if the code you sent above is related to checkout.com <https://www.checkout.com/>  payment gateway?

Thanks

**Comment by foreigntalent** [comment]
Dear Avish,

 

Sorry for the confusion, I got it mixed up as a rookie user in Github.

 

My apologies.

 

Bob

 

发件人: noreply@github.com <noreply@github.com> 代表 avish-bisbeehurry-cko
发送时间: 2018年8月13日 19:59
收件人: checkout/checkout-opencart-plugin <checkout-opencart-plugin@noreply.github.com>
抄送: foreigntalent <>; Mention <mention@noreply.github.com>
主题: Re: [checkout/checkout-opencart-plugin] Issue with reference id (#18)

 

Hi Bob,

Can you confirm if the code you sent above is related to checkout.com <https://www.checkout.com/>  payment gateway?

Thanks

**Comment by ajjagadeesh6** [comment]
Hi ,
can please sent the file api_lib.php
configuration.php
 connection.php

**Comment by foreigntalent** [comment]
Hi,

It’s all resolved.

Thanks!

Bob

Sent from thy iPhone
